import { BrandData } from './types'

export const HERMLE_MOCK: BrandData = {
  name: 'Hermle',
  slug: 'hermle',
  tagline: 'Precision that defines the standard',
  description:
    'Hermle machining centers set the global benchmark for 5-axis precision. German-engineered with mineral-cast beds, direct-drive torque motors, and micron-level repeatability — built for aerospace, medical, and mold & die.',
  categories: ['5-Axis Machining', 'CNC Precision', 'Pallet Automation'],
  heroStats: [
    { label: 'Positioning Accuracy', value: '±0.003mm' },
    { label: 'Spindle Speed',        value: '18,000 RPM' },
    { label: 'Tool Capacity',        value: '120+ Tools' },
  ],
  marqueeText:
    '5-Axis Simultaneous Machining  ·  Mineral-Cast Bed  ·  ±0.003 mm Accuracy  ·  18,000 RPM Spindle  ·  Pallet Automation  ·  German Engineering  ·  Aerospace Certified  ·  Direct-Drive Torque Motors  ·  120+ Tool Magazine  ·  ',
  productLines: [
    {
      name: 'C Series',
      seriesLabel: 'Performance',
      models: 'C 12 · C 22 · C 32 · C 42 · C 52',
      description: 'The backbone of Hermle 5-axis machining. Swivel rotary table, mineral-cast bed, exceptional dynamics for general precision work.',
      image: null,
      xTravel: '350–1000 mm',
      spindleSpeed: '18,000 RPM',
      axes: '5',
      bestFor: 'General 5-axis precision',
    },
    {
      name: 'C U Series',
      seriesLabel: 'Universal',
      models: 'C 22 U · C 32 U · C 42 U · C 52 U',
      description: 'Universal trunnion-style 5-axis centers with optimal chip evacuation and accessibility for complex contour milling.',
      image: null,
      xTravel: '450–1000 mm',
      spindleSpeed: '18,000 RPM',
      axes: '5',
      bestFor: 'Complex contour milling',
    },
    {
      name: 'C MT Series',
      seriesLabel: 'Mill-Turn',
      models: 'C 22 U MT · C 32 U MT · C 42 U MT',
      description: 'Integrated mill-turn capability combines 5-axis milling with high-torque turning in a single setup — reduced cycle time, zero re-fixturing.',
      image: null,
      xTravel: '450–800 mm',
      spindleSpeed: '18,000 RPM',
      axes: '5 + Turn',
      bestFor: 'Combined mill-turn operations',
    },
    {
      name: 'High Performance',
      seriesLabel: 'High Performance',
      models: 'C 62 U · C 650',
      description: 'Large-envelope, high-rigidity platforms for heavy aerospace and energy components. Maximum stability at scale.',
      image: null,
      xTravel: '1050–1100 mm',
      spindleSpeed: '15,000 RPM',
      axes: '5',
      bestFor: 'Large aerospace & energy parts',
    },
    {
      name: 'Automation',
      seriesLabel: 'Automated',
      models: 'HS flex · HS flex heavy · RS 05-2',
      description: 'Pallet handling and robotic systems designed for lights-out production. Seamlessly integrates with any Hermle machining center.',
      image: null,
      bestFor: 'Lights-out production',
    },
  ],
  specs: [
    { label: 'Positioning Accuracy', value: 0.003,  max: 0.01,   unit: 'mm' },
    { label: 'Spindle Speed',        value: 18000,  max: 24000,  unit: 'RPM' },
    { label: 'Rapid Traverse',       value: 60,     max: 80,     unit: 'm/min' },
    { label: 'Tool Magazine',        value: 120,    max: 200,    unit: 'tools', note: 'Expandable to 325' },
    { label: 'Table Load',           value: 2000,   max: 3000,   unit: 'kg' },
    { label: 'X-Axis Travel',        value: 1050,   max: 1500,   unit: 'mm' },
  ],
  about: {
    description:
      'Founded in Gosheim, Germany in 1938, Hermle AG has built its reputation on uncompromising precision engineering. Every Hermle machining center is manufactured in-house — from the mineral-cast machine bed to the spindle assembly — ensuring complete quality control. Hermle machines serve the world\'s most demanding industries: aerospace, medical, automotive, and precision mold & die. Phillips Corporation is the exclusive North American distributor for Hermle, providing sales, applications engineering, and service from coast to coast.',
    founded: '1938',
    employees: '1,300+',
    countries: '50+',
    inHouseMfg: '95%',
  },
  caseStudies: [
    {
      title: 'Aerospace OEM cuts cycle time 40% with 5-axis pallet automation',
      customer: 'Major Aerospace OEM',
      industry: 'Aerospace',
      summary: 'Migrated from 3-axis VMC cells to Hermle C 42 U with HS flex automation. Achieved 40% cycle time reduction and 98.7% spindle utilization.',
      slug: 'aerospace-oem-cycle-time',
    },
    {
      title: 'Medical implant manufacturer achieves sub-micron repeatability',
      customer: 'Precision Medical Corp',
      industry: 'Medical',
      summary: 'C 32 U with probing and thermal compensation enabled consistent sub-micron repeatability on titanium orthopedic implants.',
      slug: 'medical-implant-repeatability',
    },
    {
      title: 'Mold & die shop eliminates EDM steps with high-speed 5-axis',
      customer: 'Midwest Tool & Mold',
      industry: 'Mold & Die',
      summary: 'Replaced conventional EDM finishing with direct 5-axis high-speed milling on the C 22 U, cutting lead times by 60%.',
      slug: 'mold-die-edm-elimination',
    },
  ],
}
